events {
  worker_connections 1024;
}

http {
  upstream auth_service {
    server auth-service:5001;
  }

  upstream core_service {
    server core-service:5002;
  }

  upstream routing_service {
    server routing-service:5003;
  }

  upstream client_app {
    server client:5173;
  }

  server {
    listen 80;

    # Frontend
    location / {
      proxy_pass http://client_app;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
    }

    # Auth service
    location /api/auth/ {
      proxy_pass http://auth_service;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    # Core service
    location /api/core/ {
      proxy_pass http://core_service;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    # Routing service
    location /api/routing/ {
      proxy_pass http://routing_service;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
